spring:
  application:
    name: logging-framework
  main:
    allow-bean-definition-overriding: true
    allow-circular-references: true

logging:
  level:
    root: OFF
    org.springframework: OFF
    org.apache: OFF
  pattern:
    console:
  config: "classpath:log4j2.xml"

server:
  port: 8080